### ISSUE TITLE
image dimensions not followed

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rsd#12]
The image dimensions are not carried through HTML / Word:

```
image::images/xxx.jpg[height=100,width=200]
```

The following errors will be shown instead:
```
element "figure" not allowed here; expected the element end-tag, text or element "bookmark", "br", "em", "eref", "fn", "hr", "keyword", "link", "p", "pagebreak", "smallcap", "stem", "strike", "strong", "sub", "sup", "tt" or "xref" @ 350:60
element "image" not allowed here; expected the element end-tag, text or element "bookmark", "br", "dl", "em", "eref", "figure", "hr", "keyword", "link", "name", "note", "pagebreak", "pre", "smallcap", "source", "stem", "strike", "strong", "sub", "sup", "tt" or "xref" @ 351:129
found attribute "src", but no attributes allowed here @ 351:129
found attribute "id", but no attributes allowed here @ 351:129
found attribute "imagetype", but no attributes allowed here @ 351:129
found attribute "height", but no attributes allowed here @ 351:129
found attribute "width", but no attributes allowed here @ 351:129
```

**Comment by ronaldtse** [comment]
1. Explicit image dimensions are working.
2. The "auto" tag is not working. i.e:

All of these give me `height="100" width="0"`
```
image::blah.png[height=100]
image::blah.png[height=100,width=auto]
```

The current `isodoc.rng` specifies `height` and `width` to taken `int`, which should also allow auto (and default to auto, in `isodoc` gem's `blocks.rb` file:

```ruby
    def image_parse(node, out, caption)
      attrs = {
        src: node["src"],
        height: node["height"] || "auto",
        width: node["width"] || "auto"
      }
      out.img **attr_code(attrs)
      image_title_parse(out, caption)
    end
```

**Comment by opoudjis** [comment]
I will ignore both sizes if one is auto in Word; there is no way Word will understand this.

**Comment by ronaldtse** [comment]
How does height/width work in Word?

**Comment by opoudjis** [comment]
Resolved in isodoc and asciidoctor-iso.

And I don't regard this as adding value. Leaving out the width parameter would have had the same effect.

**Comment by ronaldtse** [comment]
Has anything been updated? When I leave out the "width" parameter, the HTML shows `width="0"` and the image collapses?

**Comment by opoudjis** [comment]
I have pushed both ISOdoc and Asciidoctor-iso to github. I am trying to limit pushing the gem to once a week.

**Comment by opoudjis** [comment]
You may want to change Gemfile back to pull updates from github for Isodoc and Asciidoctor-iso

**Comment by ronaldtse** [comment]
I've updated both, but I'm still getting "width=0" when I don't set `width`?

**Comment by opoudjis** [comment]
Fixed

**Comment by ronaldtse** [comment]
Thanks! IT WORKS!!!

**Comment by opoudjis** [comment]
Tweak behaviour with one parameter huge and one parameter auto: it needs to resize the one parameter down to maximum permitted size (function in Html2Doc).

**Comment by ronaldtse** [comment]
I noticed that if I do `width=600` the image in PDF will be extended out of bounds, and `width=500` fits the PDF perfectly. I wonder if we can set a `max-width:600` in the PDF HTML version so the images never break?

**Comment by opoudjis** [comment]
Similar behaviour is in fact already in place in image size handling in isodoc:

> i["width"], i["height"] = Html2Doc.image_resize(i, 800, 1200)

I need to revise the behaviour of the routine handling it to deal with the new introduction of "auto".

This currently sets the max width of images to 1200. Your request is to shrink that to 500 for PDF. That would lead to the highly lamentable step of customising HTML output expressly for PDF, so that PDFs have a smaller maximum width. (On a browser, 500 would be comically narrow.) I will see if I can enforce that kind of behaviour through CSS instead.

**Comment by ronaldtse** [comment]
@opoudjis that's why it is wise to have separate PDF HTML and HTML, since the requirements can be quite different.

Just for the sake of it, we already have Word HTML vs normal HTML and maybe there is one for PDF HTML 😉 

I am still hoping we can have a direct PDF output!

**Comment by opoudjis** [comment]
> Tweak behaviour with one parameter huge and one parameter auto: it needs to resize the one parameter down to maximum permitted size (function in Html2Doc).

Done in Html2Doc. This ticket now turns to separate PDF sizing of images.

**Comment by opoudjis** [comment]
Phew. I don't need to generate separate  PDF HTML yet, I can do it in CSS with max-width.

I will set up a separate PDF function in isodoc anyway, but it's not a pressing requirement.

**Comment by ronaldtse** [comment]
@opoudjis in fact you can put the max-width in the CSS for “media” for paper then it is only limited when we print?

**Comment by opoudjis** [comment]
Too late, I've gone ahead and realised this in isodoc after all as a separate generator (though at the moment PDF and HTML share all code, and differ in max width as a class variable).

**Comment by opoudjis** [comment]
Done
